with missionNamespace do {
	//--- Infantry
	GUER_SOLDIER = "CUP_I_TK_GUE_Soldier";
	GUER_SOLDIER_AA = "CUP_I_TK_GUE_Soldier_AA";
	GUER_SOLDIER_AR = "CUP_I_TK_GUE_Soldier_AR";
	GUER_SOLDIER_AT = "CUP_I_TK_GUE_Soldier_AT";
	GUER_SOLDIER_CREW = "CUP_I_TK_GUE_Soldier";
	GUER_SOLDIER_LAT = "CUP_I_TK_GUE_Soldier_AT";
	GUER_SOLDIER_HAT = "CUP_I_TK_GUE_Soldier_HAT";
	GUER_SOLDIER_ENGINEER = "CUP_I_TK_GUE_Mechanic";
	GUER_SOLDIER_GL = "CUP_I_TK_GUE_Soldier_GL";
	GUER_SOLDIER_MEDIC = "CUP_I_TK_GUE_Guerilla_Medic";
	GUER_SOLDIER_PILOT = "CUP_I_TK_GUE_Soldier";
	GUER_SOLDIER_SQUADLEADER = "CUP_I_TK_GUE_Soldier_TL";
	GUER_SOLDIER_SNIPER = "CUP_I_TK_GUE_Sniper";
	GUER_SOLDIER_MARKSMAN = "CUP_I_TK_GUE_Sniper";
	GUER_SOLDIER_TEAMLEADER = "CUP_I_TK_GUE_Soldier_TL";

	//--- Infantry - Mixed
	GUER_SOLDIERS_MG = [GUER_SOLDIER_AR];
	GUER_SOLDIERS_AT_LIGHT = [CUP_I_TK_GUE_Soldier_AT];
	GUER_SOLDIERS_AT_MEDIUM = [CUP_I_TK_GUE_Soldier_AT];
	GUER_SOLDIERS_AT_HEAVY = [GUER_SOLDIER_HAT];
	GUER_SOLDIERS_SPECOPS = ["CUP_I_TK_GUE_Commander"];
	GUER_SOLDIERS_ENGINEER = [GUER_SOLDIER_ENGINEER, "CUP_I_TK_GUE_Demo"];
	GUER_SOLDIERS_SNIPERS = [GUER_SOLDIER_SNIPER, "CUP_I_TK_GUE_Guerilla_Medic", "CUP_I_TK_GUE_Sniper"];
	GUER_SOLDIERS_MARKSMEN = [GUER_SOLDIER_MARKSMAN, GUER_SOLDIER_MARKSMAN, "CUP_I_TK_GUE_Guerilla_Enfield"];

	//--- Vehicles
	GUER_VEHICLES_AA_LIGHT = ["CUP_I_Ural_ZU23_TK_Gue"];
	GUER_VEHICLE_APC = ["CUP_I_BMP1_TK_GUE"]; //todo: replace with real veh later on
	GUER_VEHICLE_ARMORED_HEAVY = ["CUP_I_T55_TK_GUE"];
	GUER_VEHICLE_ARMORED_LIGHT = ["CUP_I_T34_TK_GUE"];
	GUER_VEHICLE_MOTORIZED = ["CUP_I_Datsun_PK_TK_Random","CUP_I_BTR40_MG_TKG"];
	GUER_VEHICLE_MECHANIZED = ["CUP_I_BRDM2_TK_Gue"];

	//--- Vehicles - Mixed
	GUER_VEHICLES_AA_LIGHT = GUER_VEHICLE_AA;
	GUER_VEHICLES_LIGHT = GUER_VEHICLE_MECHANIZED + GUER_VEHICLE_MOTORIZED;
	GUER_VEHICLES_MEDIUM = GUER_VEHICLE_ARMORED_LIGHT + GUER_VEHICLE_APC;
	GUER_VEHICLES_HEAVY = GUER_VEHICLE_ARMORED_HEAVY;
};