with missionNamespace do {
	//--- Infantry
	GUER_SOLDIER = "CUP_I_RACS_Soldier_Mech";
	GUER_SOLDIER_AA = "CUP_I_RACS_Soldier_AA_Mech";
	GUER_SOLDIER_AR = "CUP_I_RACS_MMG_Mech";
	GUER_SOLDIER_AT = "CUP_I_RACS_MAT_Mech";
	GUER_SOLDIER_CREW = "CUP_I_RACS_Crew";
	GUER_SOLDIER_LAT = "CUP_I_RACS_MAT_Mech";
	GUER_SOLDIER_HAT = "CUP_I_RACS_HAT_Mech";
	GUER_SOLDIER_ENGINEER = "CUP_I_RACS_Engineer_Mech";
	GUER_SOLDIER_GL = "CUP_I_RACS_GL_Mech";
	GUER_SOLDIER_MEDIC = "CUP_I_RACS_Medic_Mech";
	GUER_SOLDIER_PILOT = "CUP_I_RACS_Pilot";
	GUER_SOLDIER_SQUADLEADER = "CUP_I_RACS_SL_Mech";
	GUER_SOLDIER_SNIPER = "CUP_I_RACS_Sniper_Mech";
	GUER_SOLDIER_MARKSMAN = "CUP_I_RACS_Sniper_Mech";
	GUER_SOLDIER_TEAMLEADER = "CUP_I_RACS_Officer_Mech";

	//--- Infantry - Mixed
	GUER_SOLDIERS_MG = ["CUP_I_RACS_MMG_Mech"];
	GUER_SOLDIERS_AT_LIGHT = ["CUP_I_RACS_MAT_Mech"];
	GUER_SOLDIERS_AT_MEDIUM = ["CUP_I_RACS_HAT_Mech"];
	GUER_SOLDIERS_AT_HEAVY = ["CUP_I_RACS_HAT_Mech"];
	GUER_SOLDIERS_SPECOPS = ["CUP_I_RACS_MMG_Mech"];
	GUER_SOLDIERS_ENGINEER = [GUER_SOLDIER_ENGINEER, "CUP_I_RACS_Engineer_Mech"];
	GUER_SOLDIERS_SNIPERS = [GUER_SOLDIER_SNIPER, "CUP_I_RACS_Sniper_Mech", "CUP_I_RACS_Sniper_Mech"];
	GUER_SOLDIERS_MARKSMEN = [GUER_SOLDIER_MARKSMAN, GUER_SOLDIER_MARKSMAN, "CUP_I_RACS_Sniper_Mech"];

	//--- Vehicles
	GUER_VEHICLES_AA_LIGHT = ["CUP_I_M163_RACS"];
	GUER_VEHICLE_APC = ["CUP_I_M113_RACS"]; //todo: replace with real veh later on
	GUER_VEHICLE_ARMORED_HEAVY = ["CUP_I_T72_RACS"];
	GUER_VEHICLE_ARMORED_LIGHT = ["CUP_I_M60A3_RACS"];
	GUER_VEHICLE_MOTORIZED = ["CUP_I_LR_MG_RACS"];
	GUER_VEHICLE_MECHANIZED = ["CUP_I_AAV_RACS"];

	//--- Vehicles - Mixed
	GUER_VEHICLES_AA_LIGHT = GUER_VEHICLES_AA_LIGHT;
	GUER_VEHICLES_LIGHT = GUER_VEHICLE_MECHANIZED + GUER_VEHICLE_MOTORIZED;
	GUER_VEHICLES_MEDIUM = GUER_VEHICLE_ARMORED_LIGHT + GUER_VEHICLE_APC;
	GUER_VEHICLES_HEAVY = GUER_VEHICLE_ARMORED_HEAVY;
};